[workspace]

members = ["ike", "ike-fs", "ike-toml", "logger"]
resolver = "1"

[workspace.dependencies]
clap = { version = "4.5.11", features = ["derive"] }
anyhow = "1.0.86"
toml = "0.8.19"
serde = { version = "1", features = ["derive", "std"] }
thiserror = "1.0.63"